// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKZ-xg5ClsnhAl_x6MLx7Ji6GTpML54qM',
    appId: '1:613070071056:web:279efe5c1d79a1ac8ef195',
    messagingSenderId: '613070071056',
    projectId: 'aplicaciones-moviles-cc5a6',
    authDomain: 'aplicaciones-moviles-cc5a6.firebaseapp.com',
    storageBucket: 'aplicaciones-moviles-cc5a6.firebasestorage.app',
    measurementId: 'G-73QBB34BHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-eWPV8OAje4zTNES99Lw51Vz6muWt7RY',
    appId: '1:613070071056:android:5b83679f9b1f91da8ef195',
    messagingSenderId: '613070071056',
    projectId: 'aplicaciones-moviles-cc5a6',
    storageBucket: 'aplicaciones-moviles-cc5a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE3WkcDy5okQMQkWhztidgSNHQQPGwuGc',
    appId: '1:613070071056:ios:fb2cd8389698105c8ef195',
    messagingSenderId: '613070071056',
    projectId: 'aplicaciones-moviles-cc5a6',
    storageBucket: 'aplicaciones-moviles-cc5a6.firebasestorage.app',
    iosBundleId: 'com.example.flutterEquipo2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE3WkcDy5okQMQkWhztidgSNHQQPGwuGc',
    appId: '1:613070071056:ios:fb2cd8389698105c8ef195',
    messagingSenderId: '613070071056',
    projectId: 'aplicaciones-moviles-cc5a6',
    storageBucket: 'aplicaciones-moviles-cc5a6.firebasestorage.app',
    iosBundleId: 'com.example.flutterEquipo2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKZ-xg5ClsnhAl_x6MLx7Ji6GTpML54qM',
    appId: '1:613070071056:web:4114bf2d71cf2f448ef195',
    messagingSenderId: '613070071056',
    projectId: 'aplicaciones-moviles-cc5a6',
    authDomain: 'aplicaciones-moviles-cc5a6.firebaseapp.com',
    storageBucket: 'aplicaciones-moviles-cc5a6.firebasestorage.app',
    measurementId: 'G-80VJ4NBVX4',
  );
}
